import { describe, expect, it } from "vitest";
import { label, tsc, zpl } from "../src/index.js";
import { InvalidConfigError } from "../src/index.js";

describe("ZPL command injection hardening", () => {
  it("hex-escapes carets so text cannot break out of ^FD", () => {
    const payload = "^FS^XA^FDBOOM^XZ";
    const output = zpl.compile(label({ width: 40, height: 30 }).text(payload, { x: 10, y: 10 }));

    // Field data must not contain a raw caret anywhere
    expect(output).not.toContain("^FD" + payload + "^FS");
    const fd = output.match(/\^FD(.+?)\^FS/)!;
    expect(fd[1]).not.toContain("^");
    // Round-trips back to the original data via ^FH hex escape
    expect(fd[1]).toBe("_5EFS_5EXA_5EFDBOOM_5EXZ");
  });

  it("hex-escapes tildes (command prefix)", () => {
    const output = zpl.compile(label({ width: 40, height: 30 }).text("~JA", { x: 10, y: 10 }));
    const fd = output.match(/\^FD(.+?)\^FS/)![1];
    expect(fd).toBe("_7EJA");
  });

  it("hex-escapes underscores so they cannot be misread as escapes", () => {
    const output = zpl.compile(label({ width: 40, height: 30 }).text("a_b", { x: 10, y: 10 }));
    const fd = output.match(/\^FD(.+?)\^FS/)![1];
    expect(fd).toBe("a_5Fb");
  });

  it("hex-escapes newlines so one field stays on one line", () => {
    const output = zpl.compile(
      label({ width: 40, height: 30 }).text("line1\nline2\r\n", { x: 10, y: 10 }),
    );
    const fd = output.match(/\^FD(.+?)\^FS/)![1];
    expect(fd).toBe("line1_0Aline2_0D_0A");
    // No literal newline inside the ^FD data
    expect(fd).not.toMatch(/[\r\n]/);
  });

  it("hex-escapes non-Latin-1 characters as UTF-8 bytes", () => {
    const output = zpl.compile(label({ width: 40, height: 30 }).text("€50", { x: 10, y: 10 }));
    const fd = output.match(/\^FD(.+?)\^FS/)![1];
    expect(fd).toBe("_E2_82_AC50"); // € = E2 82 AC in UTF-8
  });

  it("leaves plain printable ASCII readable", () => {
    const output = zpl.compile(
      label({ width: 40, height: 30 }).text("Hello, World! 123", { x: 10, y: 10 }),
    );
    expect(output).toContain("^FH_^FDHello, World! 123^FS");
  });
});

describe("TSC command injection hardening", () => {
  it("neutralizes quotes and control characters in TEXT content", () => {
    const payload = 'foo"\r\nCLS\r\nPRINT 999\r\n"bar';
    const output = tsc.compile(label({ width: 40, height: 30 }).text(payload, { x: 10, y: 10 }));

    // The injection payload is fully neutralized inside a single quoted string
    const textLine = output.split("\n").find((l) => l.startsWith("TEXT "))!;
    expect(textLine).not.toMatch(/[\r\n]/);
    // Each CR/LF became one space; quotes became apostrophes
    expect(textLine).toBe('TEXT 10,10,"2",0,1,1,"foo\'  CLS  PRINT 999  \'bar"');
    // Exactly one PRINT command — the one generated by the compiler
    expect(/^PRINT \d+/m.exec(output)?.[0]).toBe("PRINT 1");
    expect(/^PRINT 999/m.exec(output)).toBeNull();
  });

  it("sanitizes BLOCK content too", () => {
    const output = tsc.compile(
      label({ width: 40, height: 30 }).text('a"b\nc', { x: 10, y: 10, maxWidth: 300 }),
    );
    const blockLine = output.split("\n").find((l) => l.startsWith("BLOCK "))!;
    expect(blockLine).not.toMatch(/[\r\n]/);
    expect(blockLine).toBe('BLOCK 10,10,300,300,"2",0,1,1,0,1,"a\'b c"');
  });

  it("strips control characters from content", () => {
    const output = tsc.compile(label({ width: 40, height: 30 }).text("a\u0000b\u001fc", { x: 10, y: 10 }));
    expect(output).toContain('"a b c"');
  });
});

describe("SVG preview escaping", () => {
  it("escapes script tags in TSC preview", () => {
    const svg = tsc.preview(
      label({ width: 40, height: 30 }).text("<script>alert(1)</script>", { x: 10, y: 10 }),
    );
    expect(svg).toContain("&lt;script&gt;");
    expect(svg).not.toContain("<script>");
  });

  it("escapes script tags in ZPL preview", () => {
    const svg = zpl.preview(
      label({ width: 40, height: 30 }).text("<img src=x onerror=alert(1)>", { x: 10, y: 10 }),
    );
    expect(svg).toContain("&lt;img");
    expect(svg).not.toContain("<img");
  });
});

describe("raw passthrough is documented trusted input", () => {
  it("passes raw commands through verbatim (intentional)", () => {
    const output = tsc.compile(label({ width: 40, height: 30 }).raw("SET CUTTER ON"));
    expect(output).toContain("SET CUTTER ON");
  });
});

describe("config validation hardening", () => {
  it("throws on NaN width", () => {
    expect(() => label({ width: NaN }).resolve()).toThrow(InvalidConfigError);
  });

  it("throws when width in dots exceeds 16-bit range", () => {
    expect(() => label({ width: 9000, unit: "mm" }).resolve()).toThrow(InvalidConfigError);
  });

  it("throws on NaN element coordinates", () => {
    expect(() =>
      label({ width: 40, height: 30 }).text("Hi", { x: NaN, y: 10 }).resolve(),
    ).toThrow(InvalidConfigError);
    expect(() =>
      label({ width: 40, height: 30 }).box({ x: 0, y: 0, width: Infinity, height: 10 }).resolve(),
    ).toThrow(InvalidConfigError);
  });

  it("validates image bitmap shape", () => {
    const bad = { data: new Uint8Array([0xff]), width: 8, height: 1, bytesPerRow: 2 };
    expect(() => label({ width: 40, height: 30 }).image(bad, { x: 10, y: 10 }).resolve()).toThrow(
      InvalidConfigError,
    );
  });
});

describe("barcode/QR command injection hardening", () => {
  it("hex-escapes ZPL barcode content so it cannot break out of ^FD", () => {
    const payload = "^FS^XA^FDBOOM^XZ";
    const out = zpl.compile(label({ width: 40, height: 30 }).barcode(payload, { x: 10, y: 10 }));
    const fd = out.match(/\^FD(.+?)\^FS/)!;
    expect(fd[1]).not.toContain("^");
    expect(fd[1]).toBe("_5EFS_5EXA_5EFDBOOM_5EXZ");
  });

  it("hex-escapes ZPL QR content", () => {
    const out = zpl.compile(label({ width: 40, height: 30 }).qrcode("~JA^XZ", { x: 10, y: 10 }));
    const fd = out.match(/\^FD(.+?)\^FS/)!;
    expect(fd[1]).toBe("_7EJA_5EXZ");
  });

  it("sanitizes TSC barcode content (quotes/CRLF)", () => {
    const out = tsc.compile(
      label({ width: 40, height: 30 }).barcode('a"\r\nPRINT 999\r\n', { x: 10, y: 10 }),
    );
    const barcodeLine = out.split("\n").find((l) => l.startsWith("BARCODE "))!;
    expect(barcodeLine).not.toMatch(/[\r\n]/);
    expect(barcodeLine).not.toContain('"a"');
    expect(out.match(/^PRINT \d+/m)?.[0]).toBe("PRINT 1");
  });

  it("sanitizes TSC QR content", () => {
    const out = tsc.compile(
      label({ width: 40, height: 30 }).qrcode('x"\r\nCLS', { x: 10, y: 10 }),
    );
    const qrLine = out.split("\n").find((l) => l.startsWith("QRCODE "))!;
    expect(qrLine).not.toMatch(/[\r\n]/);
    expect(qrLine).not.toContain('"x"');
  });

  it("raster path never embeds content as text (injection-safe by construction)", () => {
    const evil = "^FS^XA^FDINJECT^XZ";
    const out = zpl.compile(
      label({ width: 40, height: 30 }).barcode("4006381333931", { x: 10, y: 10, symbology: "ean13" }),
    );
    // ean13 is rasterized — content is pixels, not ^FD text
    expect(out).not.toContain(evil);
    expect(out).toMatch(/^\^FO10,10\^GFA,\d+,\d+,\d+,[0-9A-F]+\^FS$/m);
  });
});
